mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    ProfileListView,
    ProfileDetailView,
    ProfileUpdateView,
)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    # path("logout/", logout_view, name="logout"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),

    path("profiles/", ProfileListView.as_view(), name="profiles-list"),
    path("profiles/<int:pk>/", ProfileDetailView.as_view(), name="profile-details"),
    path("profiles/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile-update"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('myauth/', include('myauth.urls')),
]

if settings.DEBUG:
	urlpatterns.extend(
			static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	)

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):

    def profile_avatar_directory_path(instance: "Profile", filename: str) -> str:
        return "profile/{instance}/avatar/{filename}".format(
            instance=instance.user.username,
            filename=filename,
        )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to=profile_avatar_directory_path, null=True, blank=True)

mysite/myauth/forms.py
from django import forms
from .models import Profile

class AvatarUploadForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ["avatar"]

	avatar = forms.ImageField()

mysite/myauth/views.py
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, FormView, ListView, DetailView, UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin

from .models import Profile
from .forms import AvatarUploadForm


class ProfileListView(ListView):
    template_name = "myauth/profile-list.html"
    model = Profile
    context_object_name = "profiles"


class ProfileDetailView(UserPassesTestMixin, DetailView):
    template_name = "myauth/profile-detail.html"
    model = Profile
    context_object_name = "profile"

    def test_func(self):
        user = self.request.user
        profile = self.get_object()
        return user.is_staff or profile.user == user


class AboutMeView(FormView):
    form_class = AvatarUploadForm
    template_name = "myauth/about-me.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        profile.avatar = form.cleaned_data["avatar"]
        profile.save()
        return super().form_valid(form)

class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class ProfileUpdateView(UpdateView):
    model = Profile
    fields = ["avatar", "bio", "agreement_accepted"]
    template_name = "myauth/profile-update.html"
    success_url = reverse_lazy("myauth:about-me")


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
  About me
{% endblock %}


{% block body %}
  <h1>User info</h1>
  {% if user.is_authenticated %}
    <h2>Detail</h2>

    {% if user.profile.avatar %}
      <img src="{{ user.profile.avatar.url }}" alt="Avatar">
    {% else %}
      <p>No avatar</p>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update Avatar</button>
    </form>

    <p>Username: {{ user.username }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Bio: {{ user.profile.bio }}</p>

  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}

  {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}

  <form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Login</button>
  </form>
{% endblock %}

mysite/myauth/templates/myauth/profile-detail.html
{% extends "myauth/base.html" %}

{% block title %}
    Profile #{{ profile.pk }}
{% endblock %}

{% block body %}
    <h1>Profile detail:</h1>
    <div>
        <p>Username: {{ profile.user.username }}</p>
        <p>Bio: {{ profile.bio }}</p>
        <p>Agreement accepted: {{ profile.agreement_accepted }}</p>
        {% if profile.avatar %}
            <img src="{{ profile.avatar.url }}" alt="Avatar">
        {% else %}
            <p>No avatar</p>
        {% endif %}
    </div>

    <div>
        {% if request.user.is_staff or profile.user == request.user %}
            <a href="{% url 'myauth:profile-update' pk=profile.pk %}">Update profile</a>
        {% endif %}
    </div>

    <div>
        <a href="{% url 'myauth:profiles-list' %}">Back</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/profile-list.html
{% extends 'myauth/base.html' %}

{% block title %}
  Profile list
{% endblock %}

{% block body %}
  <h1>Profiles:</h1>
  {% if profiles %}
    <div>
    {% for profile in profiles %}
      <div>
        <p><a href="{% url 'myauth:profile-details' pk=profile.user.pk %}"
        >Name: {{ profile.user.username }}</a></p>
      </div>
    {% endfor %}

    </div>

  {% else %}
    <h3>No profiles yet</h3>
  {% endif %}

{% endblock %}

mysite/myauth/templates/myauth/profile-update.html
{% extends 'myauth/base.html' %}

{% block title %}
  Update profile
{% endblock %}

{% block body %}
  <h1>Update</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
  </form>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <h1>Register</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
  </form>
{% endblock %}